export const categories = [{
  "value": "",
  "label": "所有分类"
}, {
  "value": "xiaoshuo",
  "label": "有声小说"
}, {
  "value": "book",
  "label": "有声书"
}, {
  "value": "chair",
  "label": "教育培训"
}, {
  "value": "comic",
  "label": "相声评书"
}, {
  "value": "culture",
  "label": "历史"
}, {
  "value": "dianying",
  "label": "电影"
}, {
  "value": "emotion",
  "label": "情感生活"
}, {
  "value": "english",
  "label": "英语"
}, {
  "value": "entertainment",
  "label": "娱乐"
}, {
  "value": "health",
  "label": "健康养生"
}, {
  "value": "kid",
  "label": "儿童"
}, {
  "value": "music",
  "label": "音乐"
}, {
  "value": "radioplay",
  "label": "广播剧"
}, {
  "value": "renwen",
  "label": "人文"
}, {
  "value": "talk2",
  "label": "脱口秀"
}]
